version: '3'

services:

  cv.data:
    image: "microsoft/mssql-server-linux:2017-GA"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: Y
    networks:
      - cvpz
    volumes:
      - cvpz-sql-data:/var/opt/mssql

  webui:
    image: cvpz/webui
    container_name: webui
    build:
      context: ./src/WebUI
      dockerfile: Dockerfile
    networks:
      - cvpz

  identity.api:
    image: cvpz/identity.api
    container_name: identity_api
    build:
      context: ./src/Identity.api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - cv.data
    networks:
      - cvpz

  profile.api:
    image: cvpz/profile.api
    container_name: profile_api
    build:
      context: ./src/Profile.api
      dockerfile: Dockerfile
    networks:
      - cvpz

  projects.api:
    image: cvpz/projects.api
    container_name: projects_api
    build:
      context: ./src/Projects.api
      dockerfile: Dockerfile
    networks:
      - cvpz

volumes:
  cvpz-sql-data:
    external: true

networks:
  cvpz:
    driver: bridge
